import { expect, test, type Page } from '@playwright/test'
const key = 'northstar.first-mile.v1'
async function template(page: Page) {
  await page.getByRole('button', { name: 'Route a customer inquiry' }).click()
  await page.getByRole('button', { name: 'Preview template' }).click()
  await page.getByRole('button', { name: 'Use practice template' }).click()
}
async function route(page: Page) {
  await page.getByRole('button', { name: 'Preview sample route' }).click()
  await page.getByRole('button', { name: 'Confirm sample route' }).click()
}
test('deliberate route, defer, refresh, bounded undo and reset', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('./'); await template(page); await route(page)
  await expect(page.getByRole('heading', { name: 'A useful first outcome.' })).toBeVisible()
  await page.getByRole('button', { name: 'Skip for now' }).click()
  await expect(page.locator('.optional').getByText('Deferred, not completed.', { exact: false })).toBeVisible()
  await page.reload(); await expect(page.getByText('Welcome back.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preview sample route' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo practice route', exact: true }).click()
  await page.getByRole('button', { name: 'Undo sample route', exact: true }).click()
  await expect(page.getByText('Small team · applied')).toBeVisible()
  await expect(page.getByText('Waiting in Intake')).toBeVisible()
  await page.getByRole('button', { name: 'Reset practice' }).click()
  await page.getByRole('button', { name: 'Reset local practice' }).click()
  await expect(page.getByRole('heading', { name: 'Find value before finishing setup.' })).toBeVisible()
  expect(errors).toEqual([])
})
test('previews do not mutate and cancel restores focus', async ({ page }) => {
  await page.goto('./'); await page.getByRole('button', { name: 'Route a customer inquiry' }).click()
  const before = await page.evaluate(k => localStorage.getItem(k), key)
  const opener = page.getByRole('button', { name: 'Preview template' }); await opener.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(k => localStorage.getItem(k), key)).toBe(before)
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(opener).toBeFocused()
  expect(await page.evaluate(k => localStorage.getItem(k), key)).toBe(before)
  await opener.click(); await page.reload()
  await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByText('Not applied', { exact: true })).toBeVisible()
})
test('optional simulation can follow deferral and sends nothing externally', async ({ page }) => {
  const external: string[] = []; page.on('request', req => { if (!req.url().startsWith('http://127.0.0.1:4186')) external.push(req.url()) })
  await page.goto('./'); await template(page); await route(page)
  await page.getByRole('button', { name: 'Skip for now' }).click()
  await page.getByRole('button', { name: 'Preview collaborator simulation' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('.optional').getByText('Deferred, not completed.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Preview collaborator simulation' }).click()
  await page.getByRole('button', { name: 'Confirm collaborator simulation' }).click()
  await expect(page.getByText('Simulated only', { exact: true })).toBeVisible()
  await page.reload(); await expect(page.getByText('Simulated collaborator', { exact: true })).toBeVisible()
  expect(external).toEqual([])
})
test('unsupported goal has explicit limits and recoverable choice', async ({ page }) => {
  await page.goto('./'); await page.getByRole('button', { name: 'Forecasting, billing, or another goal' }).click()
  await expect(page.getByText('Only inquiry routing is supported.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preview template' })).toHaveCount(0)
  await template(page); await expect(page.getByRole('heading', { name: 'Try one real decision.' })).toBeVisible()
})
test('invalid storage stays intact until confirmed reset', async ({ page }) => {
  await page.addInitScript(k => localStorage.setItem(k, '{broken'), key)
  await page.goto('./'); await expect(page.getByRole('heading', { name: 'Let’s recover your practice.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Route a customer inquiry' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Start fresh practice' }).click(); await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await page.evaluate(k => localStorage.getItem(k), key)).toBe('{broken')
  await page.getByRole('button', { name: 'Start fresh practice' }).click(); await page.getByRole('button', { name: 'Reset local practice' }).click()
  await expect(page.getByRole('button', { name: 'Route a customer inquiry' })).toBeVisible()
})
test('storage getter unavailable explains temporary practice', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(window, 'localStorage', { get: () => { throw Error('Blocked') } }))
  await page.goto('./'); await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
  await template(page); await route(page); await expect(page.getByText('Practice route completed', { exact: true })).toBeVisible()
})
test('storage becoming unreadable retains applied template during confirmation', async ({ page }) => {
  await page.goto('./'); await template(page)
  await page.getByRole('button', { name: 'Preview sample route' }).click()
  await page.evaluate(() => Object.defineProperty(window, 'localStorage', { get: () => { throw Error('Newly blocked') } }))
  await page.getByRole('button', { name: 'Confirm sample route' }).click()
  await expect(page.getByText('Small team · applied')).toBeVisible()
  await expect(page.getByText('Practice route completed', { exact: true })).toBeVisible()
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
})
test('same revision divergent storage cannot confirm stale preview', async ({ page }) => {
  await page.goto('./'); await template(page); await page.getByRole('button', { name: 'Preview sample route' }).click()
  await page.evaluate(k => { const s = JSON.parse(localStorage.getItem(k)!); localStorage.setItem(k, JSON.stringify({ ...s, goal: 'other', setup: false })) }, key)
  await page.getByRole('button', { name: 'Confirm sample route' }).click()
  await expect(page.getByText('This preview is out of date.', { exact: false })).toBeVisible()
  await expect(page.getByText('Waiting in Intake')).toBeVisible()
})
test('another tab invalidates an open preview', async ({ page, context }) => {
  await page.goto('./'); await template(page); await page.getByRole('button', { name: 'Preview sample route' }).click()
  const other = await context.newPage(); await other.goto('./')
  await other.getByRole('button', { name: 'Reset practice' }).click(); await other.getByRole('button', { name: 'Reset local practice' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('Saved practice changed in another tab.', { exact: false })).toBeVisible()
  await expect(page.getByText('Not applied', { exact: true })).toBeVisible()
})
test('keyboard reaches outcome with focus and announcements', async ({ page }) => {
  await page.goto('./'); await page.keyboard.press('Tab'); await expect(page.getByRole('link', { name: 'Skip to practice' })).toBeFocused()
  await page.keyboard.press('Enter')
  const goal = page.getByRole('button', { name: 'Route a customer inquiry' }); await goal.focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'A small team. A clear route.' })).toBeFocused()
  const open = page.getByRole('button', { name: 'Preview template' }); await open.focus(); await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
  await page.keyboard.press('Tab'); await expect(page.getByRole('button', { name: 'Use practice template' })).toBeFocused(); await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Preview sample route' }).focus(); await page.keyboard.press('Enter'); await page.keyboard.press('Tab'); await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'A useful first outcome.' })).toBeFocused()
  await expect(page.locator('[aria-live="polite"]')).toContainText('NS-104 routed to Customer care')
})
test('narrow layout keeps primary and recovery actions visible', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('./')
  await page.screenshot({ path: 'test-results/mobile-entry.png', fullPage: true })
  await template(page); await route(page); await page.getByRole('button', { name: 'Skip for now' }).click()
  await page.screenshot({ path: 'test-results/mobile-outcome.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Reset practice' }).click(); await page.getByRole('button', { name: 'Reset local practice' }).click()
})
test('production metadata and reviewer artifacts are reachable', async ({ page, request }) => {
  await page.goto('./'); await page.screenshot({ path: 'test-results/desktop-entry.png', fullPage: true })
  await expect(page.locator('meta[http-equiv="Content-Security-Policy"]')).toHaveAttribute('content', /connect-src 'self'/)
  await expect(page.locator('meta[name="referrer"]')).toHaveAttribute('content', 'no-referrer')
  for (const file of ['Case_Study', 'Sample_Contract', 'Sample_Walkthrough']) expect((await request.get(`docs/product/${file}.md`)).ok()).toBe(true)
})
test('route and reset cancellation preserve confirmed progress', async ({ page }) => {
  await page.goto('./'); await template(page)
  const before = await page.evaluate(k => localStorage.getItem(k), key)
  await page.getByRole('button', { name: 'Preview sample route' }).click(); await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByText('Waiting in Intake')).toBeVisible()
  await page.getByRole('button', { name: 'Reset practice' }).click(); await page.keyboard.press('Escape')
  expect(await page.evaluate(k => localStorage.getItem(k), key)).toBe(before)
  await route(page); await expect(page.getByText('Practice route completed', { exact: true })).toBeVisible()
})
test('quota write failure retains confirmed route with temporary warning', async ({ page }) => {
  await page.goto('./'); await template(page)
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError') } })
  await route(page)
  await expect(page.getByText('Small team · applied')).toBeVisible()
  await expect(page.getByText('Practice route completed', { exact: true })).toBeVisible()
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
  await page.reload(); await expect(page.getByText('Waiting in Intake')).toBeVisible()
})
test('unreadable getItem preserves unseen bytes through goal template route and reset', async ({ page }) => {
  await page.addInitScript(k => {
    const originalRead = Storage.prototype.getItem
    localStorage.setItem(k, '{unseen-invalid')
    Object.defineProperty(window, '__readSaved', { value: () => originalRead.call(localStorage, k) })
    Storage.prototype.getItem = () => { throw new DOMException('Read blocked', 'SecurityError') }
  }, key)
  const saved = () => page.evaluate(() => (window as unknown as { __readSaved: () => string }).__readSaved())
  await page.goto('./')
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Route a customer inquiry' }).click()
  expect(await saved()).toBe('{unseen-invalid')
  await page.getByRole('button', { name: 'Preview template' }).click()
  await page.getByRole('button', { name: 'Use practice template' }).click()
  expect(await saved()).toBe('{unseen-invalid')
  await route(page)
  expect(await saved()).toBe('{unseen-invalid')
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Reset practice' }).click()
  await page.getByRole('button', { name: 'Reset local practice' }).click()
  expect(await saved()).toBe('{unseen-invalid')
  await expect(page.getByRole('button', { name: 'Route a customer inquiry' })).toBeVisible()
})
test('getItem becoming unreadable retains prior bytes and route until explicit readable reset', async ({ page }) => {
  await page.goto('./'); await template(page)
  const before = await page.evaluate(k => localStorage.getItem(k), key)
  await page.evaluate(k => {
    const originalRead = Storage.prototype.getItem
    Object.defineProperty(window, '__readSaved', { value: () => originalRead.call(localStorage, k) })
    Object.defineProperty(window, '__restoreRead', { value: () => { Storage.prototype.getItem = originalRead } })
    Storage.prototype.getItem = () => { throw new DOMException('Read blocked', 'SecurityError') }
  }, key)
  const saved = () => page.evaluate(() => (window as unknown as { __readSaved: () => string }).__readSaved())
  await route(page)
  expect(await saved()).toBe(before)
  await expect(page.getByText('Practice route completed', { exact: true })).toBeVisible()
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Skip for now' }).click()
  expect(await saved()).toBe(before)
  await page.getByRole('button', { name: 'Reset practice' }).click()
  await page.getByRole('button', { name: 'Reset local practice' }).click()
  expect(await saved()).toBe(before)
  await page.evaluate(() => (window as unknown as { __restoreRead: () => void }).__restoreRead())
  await page.getByRole('button', { name: 'Route a customer inquiry' }).click()
  expect(await saved()).toBe(before)
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Reset practice' }).click()
  await page.getByRole('button', { name: 'Reset local practice' }).click()
  const reset = JSON.parse((await saved())!)
  expect(reset).toMatchObject({ goal: null, setup: false, routed: false, collaborator: 'pending' })
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await template(page); await route(page); await page.reload()
  await expect(page.getByText('Practice route completed', { exact: true })).toBeVisible()
})
test('reads becoming blocked on goal selection preserve unknown invalid bytes', async ({ page }) => {
  await page.goto('./')
  await page.evaluate(k => {
    const originalRead = Storage.prototype.getItem
    localStorage.setItem(k, '{unseen-after-entry')
    Object.defineProperty(window, '__readSaved', { value: () => originalRead.call(localStorage, k) })
    Storage.prototype.getItem = () => { throw new DOMException('Read blocked', 'SecurityError') }
  }, key)
  await page.getByRole('button', { name: 'Route a customer inquiry' }).click()
  expect(await page.evaluate(() => (window as unknown as { __readSaved: () => string }).__readSaved())).toBe('{unseen-after-entry')
  await expect(page.getByRole('heading', { name: 'A small team. A clear route.' })).toBeVisible()
  await expect(page.getByText('Browser storage is unavailable.', { exact: false })).toBeVisible()
})
